const employeesData = [
  {
    key: "1",
    name: "Alice Johnson",
    department: "Engineering",
    position: "Software Engineer",
    email: "alice.j@example.com",
    city: "New York",
    phone: "1234567890",
    salary: 90000,
    performanceScore: 85,
    projectsCompleted: 7,
    salesNumbers: 0,
    customerSatisfaction: 78,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 5,
    taskStatus: "In Progress",
  },
  {
    key: "2",
    name: "Bob Smith",
    department: "HR",
    position: "HR Manager",
    email: "bob.s@example.com",
    city: "London",
    phone: "2345678901",
    salary: 80000,
    performanceScore: 90,
    projectsCompleted: 5,
    salesNumbers: 0,
    customerSatisfaction: 92,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 2,
    taskStatus: "Completed",
  },
  {
    key: "3",
    name: "Charlie Davis",
    department: "Marketing",
    position: "Marketing Executive",
    email: "charlie.d@example.com",
    city: "Paris",
    phone: "3456789012",
    salary: 70000,
    performanceScore: 88,
    projectsCompleted: 6,
    salesNumbers: 12,
    customerSatisfaction: 85,
    activeUsers: false,
    newUsers: true,
    assignedTasks: 4,
    taskStatus: "Pending",
  },
  {
    key: "4",
    name: "Diana Peters",
    department: "Finance",
    position: "Financial Analyst",
    email: "diana.p@example.com",
    city: "Tokyo",
    phone: "4567890123",
    salary: 75000,
    performanceScore: 82,
    projectsCompleted: 4,
    salesNumbers: 0,
    customerSatisfaction: 80,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 3,
    taskStatus: "In Progress",
  },
  {
    key: "5",
    name: "Evan Green",
    department: "Engineering",
    position: "DevOps Engineer",
    email: "evan.g@example.com",
    city: "Paris",
    phone: "5678901234",
    salary: 92000,
    performanceScore: 91,
    projectsCompleted: 8,
    salesNumbers: 0,
    customerSatisfaction: 89,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 6,
    taskStatus: "Completed",
  },
  {
    key: "6",
    name: "Fiona White",
    department: "HR",
    position: "Recruitment Lead",
    email: "fiona.w@example.com",
    city: "New York",
    phone: "6789012345",
    salary: 72000,
    performanceScore: 84,
    projectsCompleted: 4,
    salesNumbers: 0,
    customerSatisfaction: 87,
    activeUsers: false,
    newUsers: true,
    assignedTasks: 1,
    taskStatus: "Pending",
  },
  {
    key: "7",
    name: "George Black",
    department: "Sales",
    position: "Sales Representative",
    email: "george.b@example.com",
    city: "Singapore",
    phone: "7890123456",
    salary: 68000,
    performanceScore: 78,
    projectsCompleted: 3,
    salesNumbers: 18,
    customerSatisfaction: 82,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 4,
    taskStatus: "In Progress",
  },
  {
    key: "8",
    name: "Hannah Brown",
    department: "Marketing",
    position: "Content Strategist",
    email: "hannah.b@example.com",
    city: "Rome",
    phone: "8901234567",
    salary: 73000,
    performanceScore: 86,
    projectsCompleted: 5,
    salesNumbers: 15,
    customerSatisfaction: 88,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 2,
    taskStatus: "Completed",
  },
  {
    key: "9",
    name: "Ian Turner",
    department: "Finance",
    position: "Accountant",
    email: "ian.t@example.com",
    city: "Paris",
    phone: "9012345678",
    salary: 78000,
    performanceScore: 80,
    projectsCompleted: 3,
    salesNumbers: 0,
    customerSatisfaction: 81,
    activeUsers: false,
    newUsers: true,
    assignedTasks: 1,
    taskStatus: "Pending",
  },
  {
    key: "10",
    name: "Julia Adams",
    department: "Engineering",
    position: "Frontend Developer",
    email: "julia.a@example.com",
    city: "London",
    phone: "1230984567",
    salary: 87000,
    performanceScore: 89,
    projectsCompleted: 6,
    salesNumbers: 0,
    customerSatisfaction: 90,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 5,
    taskStatus: "In Progress",
  },
  {
    key: "11",
    name: "Kevin Miller",
    department: "Sales",
    position: "Sales Manager",
    email: "kevin.m@example.com",
    city: "Singapore",
    phone: "2341098765",
    salary: 96000,
    performanceScore: 92,
    projectsCompleted: 4,
    salesNumbers: 25,
    customerSatisfaction: 94,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 6,
    taskStatus: "Completed",
  },
  {
    key: "12",
    name: "Laura Young",
    department: "HR",
    position: "HR Executive",
    email: "laura.y@example.com",
    city: "Madrid",
    phone: "3452109876",
    salary: 71000,
    performanceScore: 83,
    projectsCompleted: 3,
    salesNumbers: 0,
    customerSatisfaction: 86,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 3,
    taskStatus: "Pending",
  },
  {
    key: "13",
    name: "Mike Robinson",
    department: "Engineering",
    position: "Backend Developer",
    email: "mike.r@example.com",
    city: "Madrid",
    phone: "4563210987",
    salary: 88000,
    performanceScore: 87,
    projectsCompleted: 7,
    salesNumbers: 0,
    customerSatisfaction: 88,
    activeUsers: true,
    newUsers: false,
    assignedTasks: 4,
    taskStatus: "In Progress",
  },
];

export default employeesData;
